services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: berwobeto@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: bernardo13
  #   ports:
  #     - "8080:80"